//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPurchasingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey
    {
        public int JourneyID { get; set; }
        public string JourneyStart { get; set; }
        public string CoatchType { get; set; }
        public string JourneyEnd { get; set; }
        public Nullable<System.DateTime> JourneyDate { get; set; }
        public Nullable<int> TokenNumber { get; set; }
        public string TimeOfJourney { get; set; }
        public Nullable<int> PersonID { get; set; }
    }
}
