//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPurchasingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonID { get; set; }
        public string PersonName { get; set; }
        public string PersonFathersName { get; set; }
        public string PersonMothersName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PersonAddress { get; set; }
    }
}
